services:

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: database_data/
        target: /database_data
