services:
  backend:
    env_file: .env
    build:
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - type: bind
        source: database_data/
        target: /database_data
      - type: bind
        source: ./backend
        target: /backend

  # frontend-prod:
  #   env_file: .env
  #   build:
  #     context: frontend/.
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # keep container's node_modules, not host's
    environment:
      - CHOKIDAR_USEPOLLING=true # needed for file change detection in Docker
